# Site settings
author: Jason Yoon
title: Data Science for Mechanical Engineer
header-img: img/home-bg.png
email: gwonchanyoon@gmail.com
copyright_name: Jason Yoon
description: > # this means to ignore newlines until "baseurl:"
  .
baseurl: "/startbootstrap-clean-blog-jekyll" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  gwonchan

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
