# Site settings
author: Gwonchan Jason Yoon
title: AVICS FOREVER@KOREA UNIVERSITY
header-img: img/home-bg.png
email: gwonchanyoon@gmail.com
copyright_name: Gwonchan Jason Yoon
description: > # this means to ignore newlines until "baseurl:"
  .
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  gwonchan

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
